### ISSUE TITLE
Class-5 Bedtools Exercises

### ISSUE THREAD

**Issue by mackie90125** [MOLB7621/Discussion#10]
After working through the [Class-5 Bedtools Exercises](http://molb7621.github.io/workshop/Classes/class-05.html#exercises), I can get the correct answer for all of them except Question 6.

*Question 6:* Report genes that overlap more than 1 CpG Island (use -c and awk). [3703].
```
bedtools intersect -a genes.hg19.bed.gz -b cpg.bed.gz -c | awk '$7 > 1' | wc -l
```
My output for this is: 3714

Am I doing something wrong? Or is the given answer of 3703 incorrect?

**Comment by jayhesselberth** [comment]
What happens if you flip the a and b files e.g.
```
bedtools intersect -a cpg.bed.gz -b genes.hg19.bed.gz -c | awk '$7 > 1' | wc -l
```

**Comment by mackie90125** [comment]
If the a and b files are flipped:

```
bedtools intersect -a cpg.bed.gz  -b genes.hg19.bed.gz -c | awk '$5 > 1' | wc -l
```
The output is: 2610
*(and note that the column for awk has changed)*

But wouldn't this be answering a different question? This would report CpGs that intersect genes, not genes that intersect CpGs.

In any case, the specific answer to Question-6 is not important; I just want to make sure I am understanding the use of Bedtools correctly.
