### ISSUE TITLE
RStudio next week (class 8)

### ISSUE THREAD

**Issue by jayhesselberth** [MOLB7621/Discussion#11]
Install RStudio before class next week. 

Also you should install several packages in RStudio:

``` r
install.packages(c('dplyr','readr','ggplot2','rmarkdown'), dep = TRUE)
```

**Comment by ericlarson84** [comment]
Anyone running Linux, make sure you have the latest version of R.  I was on 3.0.2 and couldn’t get these packages installed.  However, upgrading to 3.2.3 fixed it.  
After updating R, make sure to restart RStudio session - it will display the version number in the console
