### ISSUE TITLE
Audio for class Feb 18 class recording?

### ISSUE THREAD

**Issue by tstastny03** [MOLB7621/Discussion#13]
Hi All,

Is anyone able to hear the audio recording for yesterday's class?  I can hear the Genome Browser lecture, but not 'Class 7'.

Thank you!
Tiana

**Comment by jayhesselberth** [comment]
I can't win with these video recordings. Luckily we spent 90% of the class with the students doing the problem sets. I did go over (verbally) the approach for all of them so let me know if you want me to reiterate.
