### ISSUE TITLE
Practicing BEDtools

### ISSUE THREAD

**Issue by jayhesselberth** [MOLB7621/Discussion#14]
We are going to move on from [BEDtools](http://bedtools.readthedocs.org/en/latest/content/bedtools-suite.html) next week, but you should keep practicing with the tools. Here are some resources to keep you going.
## Installs and Downloads
1. The [ENCODE data downloads](http://genome.ucsc.edu/ENCODE/downloads.html) are a good place to get raw data to work with. You can start with the integrated ChIP and DNase tracks contain peak calls in BED format. You should also pay attention to the cell types in which the experiments were performed, which are coded as numbers in some of the files.
2. You will also need to install a few utilities to work with the files. Tools for converting from binary bigWig (`.bw`) and bigBed (`.bb`) file to plain text (`bedGraph` and `bed`, respectively)
3. The [UCSC Table Browser](https://genome.ucsc.edu/cgi-bin/hgTables) gives you access to annotation tracks (e.g., genes). For example, go get the `RefSeq` genes for `hg19` in gzip-compressed `BED` format.
   - On a Mac, you can do `brew install kent-tools` to install the `bigWigToBedGraph` and `bigBedToBed` utilities.
   - On tesla, do `module load ucsc`.
   - On Linux, download the [executables](http://hgdownload.soe.ucsc.edu/admin/exe/) and put them in your `PATH`.
## Questions

Once you have all of this installed, you can starting asking questions:
- What factor is associated with the most DNase I hypersensitive peaks (focus on `chr22` to keep the run times short).
- What cell type has the most CTCF binding sites?
- Are there factors that are bound excessively in specific cell types (i.e. cell-type-specific factors)?
- Can you identify [enhancer RNAs](http://www.cell.com/trends/biochemical-sciences/abstract/S0968-0004%2814%2900032-2) in the ENCODE data? (i.e. start by identifying non-promoter associated transcription).
## Other resources
1. [This page](https://github.com/arq5x/bedtools-protocols/blob/master/bedtools.md) contains BEDtools workflows (we went over the ChIP workflow in class).

**Comment by ericlarson84** [comment]
For " other resources" I think [this page](http://quinlanlab.org/tutorials/bedtools/bedtools.html) is a more updated version

I wasn't able to download all of the bed files suggested in the original link.
