### ISSUE TITLE
Git & GitHub resources for new users

### ISSUE THREAD

**Issue by lkwhite** [MOLB7621/Discussion#2]
If you had trouble wrapping your mind around Git (the version control system that you can use in the command line & that also underpins GitHub), GitHub.org (this repository-hosting website where Jay's hosting the course), and GitHub Desktop (the desktop client you downloaded & installed), here are a few videos that I've used in a previous class:
- [Introduction to Git](https://www.youtube.com/watch?v=7t0trLYF16Q) - (note: we installed Git from the command line using Homebrew or your Linux package manager of choice in class instead of with the Windows installer shown here)
- [Introduction to GitHub](https://www.youtube.com/watch?v=nL4wIp6n1hA)
- [Creating a GitHub Repository](https://www.youtube.com/watch?v=IPoZ9jPOtb8) (without using the GitHub desktop client)
- [Basic Git Commands](https://www.youtube.com/watch?v=0pdu0xkLMgA)

Each video's about 5 mins. They are a few years old (they're from a course that reruns frequently on Coursera), so the user interface on the website & client probably looks a little bit different, but all the basics should be the same.

**Comment by lkwhite** [comment]
Also if you prefer reading over videos, GitHub's got its own 101 for new users [here](https://guides.github.com/activities/hello-world/) and a rew more guides to doing specific things [here] (https://guides.github.com).

**Comment by jayhesselberth** [comment]
In the long run, it may be easier to forego the client and just learn command line git.
