### ISSUE TITLE
Book Recomendation

### ISSUE THREAD

**Issue by jayhesselberth** [MOLB7621/Discussion#22]
@sandymartin recommends "Python for Biologists" as a good book that "explains everything" (I am not taking this personally).

http://pythonforbiologists.com/

**Comment by lkwhite** [comment]
I noticed [Datacamp](www.datacamp.com)'s finally added some Python tutorials as well. (First one's free, the intermediate one is at their $9/mo academic subscription price.) They do everything in an interactive web interface. Pretty different style from Zed (explanations _then_ exercises, how novel), but covering a lot of the same ground.
