### ISSUE TITLE
Final Project Presetations

### ISSUE THREAD

**Issue by jayhesselberth** [MOLB7621/Discussion#23]
When: **May 12, 2:00-4:00 PM** (note change from normal class time)
Where: RC1 South 9th floor conference room

Please plan to present 3-4 slides including the setup (background / hypothesis), a pretty graph / genome browser session, and some code that you are particularly proud of.

@MOLB7621/students @MOLB7621/tas

**Comment by menzelj** [comment]
Hello Jay

I have an idea for the final project but I am not sure how exactly to approach it.
Does replication timing correlate with gene copy number?

I found some files on ENCODE for copy number and for replication timing, both in the same cell lines. Could I perhaps select some genes with CNV and see if there is any correlation with early or late replication.
Please let me know if you think this is something I could pull off with my meager genomic analysis and programing skills.

Thanks
Johannes



________________________________

**Comment by jayhesselberth** [comment]
Seems like a reasonable hyphothesis (not sure if anyone has actually looked at it).

The replication timing data is likely already in BED format so it might be matter of measuring the amount of early / late segments within some distance of genes with known CNV.

**Comment by jayhesselberth** [comment]
Looking forward to seeing all of your presentations on Thursday. Please plan to bring a laptop, there are HDMI / VGA connections in the room.

When: May 12, 2:00-4:00 PM (note change from normal class time)
Where: RC1 South 9th floor conference room

@MOLB7621/students @MOLB7621/tas @MOLB7621/instructor

**Comment by jayhesselberth** [comment]
Please submit the documents for your final projects in the final projects repository.

https://github.com/MOLB7621/finalprojects

@MOLB7621/students
