### ISSUE TITLE
problem set 2 git commit error

### ISSUE THREAD

**Issue by hooperj** [MOLB7621/Discussion#33]
git commit is not recognizing either my answers.sh or my answers.yml files.
`git commit -m "ps2 code.1" answers.sh`

> error: pathspec 'answers.sh' did not match any file(s) known to git.

so how are we supposed to upload our answers?

**Comment by kriemo** [comment]
Double check that when you run `git commit` that you are in the `problem-set-2` directory. 

If that doesn't work, when you are in the `problem-set-2` directory, what is the output when you run `git status`?

**Comment by jayhesselberth** [comment]
Make git aware of the files:

```bash
git add answers.sh
git commit -m 'msg' answers.sh
```
