### ISSUE TITLE
RE: hg19.chr22.fa

### ISSUE THREAD

**Issue by casey-martin** [MOLB7621/Discussion#34]
@jayhesselberth 

When printing the contents of hg19.chr22.fa to screen, nucleotide bases are reported as "N". However, when performing the bedtools nuc analysis, no "N's" are returned, only standard nucleotides. Do you know why this is happening?

Thanks,
Casey

**Comment by jayhesselberth** [comment]
The telomeres of the chromsome (i.e., start and end) are N's. If you scroll down (or just search for "A" with `less`) you'll see where the real sequence starts. `bedtools nuc` ignores N positions.

**Comment by casey-martin** [comment]
Much appreciated!
