### ISSUE TITLE
Office Hours

### ISSUE THREAD

**Issue by jayhesselberth** [MOLB7621/Discussion#5]
I have reserved the conference room on the 10th floor of RC1 South for office hours on Fridays from 1:00 to 2:30pm. Feb 12 and 19 were taken so we will have to find a temporary solution for those days if there is interest.

BTW if you are not "watching" this repo, you probably should be. Click the "watch" button above.

@MOLB7621/tas @MOLB7621/students

**Comment by sheridar** [comment]
The RC1S 9th floor conference room is open today from 1-2:30pm. Could somebody reserve it? My account with the room reservation system is still "pending".

**Comment by sheridar** [comment]
Office hours are from 1-2:30pm today in RC1S 9th conference room
