### ISSUE TITLE
awk in-class exercises

### ISSUE THREAD

**Issue by mackie90125** [MOLB7621/Discussion#6]
Regarding the [in-class exercise 4](http://molb7621.github.io/workshop/Classes/class-04.html#in-class-exercise) for awk, what would be the best and/or most efficient way to answer this question:

Question-4: how many regions in lamina.bed overlap the interval chr12:5,000,000-6,000,000 ?

This is what I came up with:

```awk '( $1 == "chr12" && $2 < 6000000 && $3 > 5000000)' lamina.bed ```

Is there a better/more efficient/more correct way of answering this problem?
It's marked as being important in the outline, so I figure we should know the best way to go about it.

**Comment by jayhesselberth** [comment]
right idea but I think it should be like this:

```
awk '$1 == "chr12" && $2 >= 5000000 && $3 <= 6000000' lamina.bed
```
