### ISSUE TITLE
Grep in-class excercise#1

### ISSUE THREAD

**Issue by ericlarson84** [MOLB7621/Discussion#7]
"use grep to identify lines in lamina.bed where the second field (start) begins with 100."

```
cut -f2 lamina.bed | grep '^100' 
```

While this seems to work, it just dumps out the column 2 value starting with 100.  What if I wanted the output to show which chromosome each line was on?  

I think what I want is to "grep" lines where column 2 starts with 100.  Am I just forgetting an option for 'grep'?

I was able to do using awk to simply reorder the columns, but it seems a bit convoluted.
```
cat lamina.bed | awk '{print $2,$3,$4,$1}' | grep '^100'
```

**Comment by jayhesselberth** [comment]
We will go over this in class tomorrow but the general idea is to use the `~` operator to do matching.
```
awk '$2 ~ "^100"' lamina.bed
```
