### ISSUE TITLE
Plot of Bedtools ChIP Analysis from today's class 2-11-16

### ISSUE THREAD

**Issue by mackie90125** [MOLB7621/Discussion#8]
Here is the plot I made from today's analysis of ChIP data using Bedtools
Just in case anyone is curious
![plot](https://cloud.githubusercontent.com/assets/16945100/12995790/601f318c-d0e7-11e5-9972-e740745ce92a.jpg)

and the R code if you're interested

``` R
signal_data = read.csv("signal.csv", header = FALSE)
signal_data$V1 = seq(-950,1000, length.out = 40)

jpeg("D:/Genome Analysis Workshop/bedtools-test/plot.jpg")
par(yaxt = "n")
plot.default(signal_data, type = "l", col = "blue",
             main = "Protein Binding at TSS for chr22",
             xlab = "bp surrounding TSS",
             ylab = NA)
mtext("Signal 'Protein Binding'", side = 2, line = 1)
dev.off()
```

**Comment by jayhesselberth** [comment]
Can you post the first 10 lines of `signal.csv`?

**Comment by jayhesselberth** [comment]
I added all files to `data-sets/bedtools/class-5`.

New R is easier on the eyes.

```R
# install.packages(c('readr', 'dplyr', 'cowplot'))
library(readr)
library(dplyr)
library(cowplot)

tab <- read_tsv('signal.tab', col_names = c('pos', 'signal'))

tab <- tab %>% mutate(coord = seq(-1000, 1000, length.out = 40))
         
gp <- ggplot(tab, aes(x = coord, y = signal))
gp <- gp + geom_point() + geom_line() + geom_vline(xintercept = 0, color = 'red')
gp <- gp + xlim(c(-1000, 1000))
gp <- gp + xlab('Position (bp)') + ylab('Signal (arbitrary units)')
gp <- gp + ggtitle('CTCF binding near TSS on chr22')

gp
# ggsave('plot.png', gp)
```
![plot](https://cdn.rawgit.com/MOLB7621/data-sets/master/bedtools/class-5/plot.png)

**Comment by mackie90125** [comment]
I can only assume that this will quickly progress into a competition of who can make the best graph.

**Comment by jayhesselberth** [comment]
It is ON.

**Comment by jayhesselberth** [comment]
Extra credit to anyone that implements interactive visualization of this plot with `shiny`.

**Comment by mackie90125** [comment]
Shiny is pretty sweet. [New interactive graph here.](https://mackie90125.shinyapps.io/ChIP_app/)
